Fix some static library creation
    Static library are created with more accuracy.
    Additional allow the project to specify the minimum coverage.

diff --git a/tools/Makefile b/tools/Makefile
--- a/tools/Makefile
+++ b/tools/Makefile
@@ -59,6 +59,8 @@
 #	FILE_WARNING_FLAGS
 #		Extra project specific warning flags
 #
+#	COVERAGE_REQUIRED defaults to 80%
+#		but if you want to reduce this you can set this in a specific project make file
 #
 
 -include $(THORSANVIL_ROOT)/Makefile.config
@@ -66,10 +68,13 @@ BUILD_ROOT		?= $(THORSANVIL_ROOT)/build
 include $(BUILD_ROOT)/tools/Colour.Makefile
 include $(BUILD_ROOT)/tools/Platform.Makefile
 
+COVERAGE_REQUIRED	?= 80
+
 YACC			= bison
 LEX				= flex
 GPERF			= gperf --ignore-case
 CP				= cp
+
 CXX				= $(CXX_$(TARGET_MODE))
 COV				= gcov$(CXX_coverage_$(PLATFORM)$(PLATFORMVER))
 MKTEMP			= $(MKTEMP_$(PLATFORM))
@@ -82,6 +87,10 @@ CXX_profile		= g++$(CXX_profile_$(PLATFORM)$(PLATFORMVER))
 #
 # This is obviously not working
 # Need to look at this
+COV_LONG_FLAG			= $(COV_LONG_FLAG_$(PLATFORM))
+COV_LONG_FLAG_Linux		= --long-file-names
+COV_LONG_FLAG_Darwin	= -p 
+
 CXX_coverage_Darwin11_3_0		= -4.2
 CXX_profile_Darwin11_3_0		= -4.2
 
@@ -248,10 +257,10 @@ BUILD_EXTENSION_TYPE_profile	=	P
 all:	PrintDebug buildDir Note_Building_$(TARGET_MODE) $(TARGET)
 	@echo $(call colour_text, BLUE, "Done")
 validate:		test 
-install:		test try_install_head try_install_Dodebug try_install_Dorelease
-install_debug:	test try_install_head try_install_Dodebug
-install_release:test try_install_head try_install_Dorelease
-install_profile:     try_install_head try_install_Doprofile
+install:		test try_install_head install_Dodebug install_Dorelease
+install_debug:	test try_install_head install_Dodebug
+install_release:test try_install_head install_Dorelease
+install_profile:     try_install_head install_Doprofile
 header_only:	test try_install_head
 
 tools:
@@ -345,21 +354,33 @@ test_%:
 
 coverage:	$(GCOV_REPORT) $(patsubst coverage/%.gcov, report_coverage_%, $(GCOV_REPORT))
 	@if [ "$(GCOV_ACTUAL)" != "" ]; then								\
-		 left=`cat $(GCOV_ACTUAL) | grep '####' | wc -l`;				\
-		 right=`cat $(GCOV_ACTUAL)| grep -v '\-:' | wc -l`;				\
-		 a=$${right};b=$${left};c=$$(($$a-$$b));d=$$(($$c*100));e=$$(($$d/$$a));		\
-		 res=`echo "$${left} > ($${right}  * 0.2)"  | bc`;				\
+		 linesNotTested=`cat $(GCOV_ACTUAL) | grep '####' | wc -l`;		\
+		 linesTestable=`cat $(GCOV_ACTUAL)| grep -v '\-:' | wc -l`;		\
+		 linesTested=$$(($${linesTestable}-$${linesNotTested}));		\
+		 linesTested100=$$(($${linesTested}*100));						\
+		 coverage=$$(($${linesTested100}/$${linesTestable}));			\
+		 res=`echo "scale=2;$${linesNotTested} > ($${linesTestable} * ((100-$(COVERAGE_REQUIRED))/100))" | bc`;				\
 		 if [ $${res} -ne 0 ]; then										\
-			echo $(RED_ERROR) $(call colour_text, PURPLE, Code Coverage $${e}% does not exceed 80% of total);	\
+			echo $(RED_ERROR) $(call colour_text, PURPLE, Code Coverage $${coverage}% does not exceed $(COVERAGE_REQUIRED)% of total);	\
 			echo "Use: '$(MAKE) test VERBOSE=$(VERBOSE) PREFIX=$(PREFIX) CXXSTDVER=$(CXXSTDVER) COVERAGE=On' to get details about coverage";		\
 			exit 1;														\
 		 else															\
 			echo $(GREEN_OK) Code Coverage Passed;						\
 		 fi																\
 	 fi
+
 coverage/%.cpp.gcov: always
 	@echo "Generating Coverage for $*.cpp"
-	@if [ -e $*.cpp ]; then $(COV) --long-file-names --object-directory coverage $*.cpp 2>/dev/null	> coverage/$*.cpp.out ; fi;
+	@if [ -e $*.cpp ]; then												\
+		echo $(COV) $*.cpp ;											\
+		$(COV) $(COV_LONG_FLAG) --object-directory coverage $*.cpp 2> coverage_tmp	> coverage/$*.cpp.out ;			\
+		if [ $$? != 0 ]; then											\
+			echo "$(COV) $(COV_LONG_FLAG) --object-directory coverage $*.cpp 2> coverage_tmp > coverage/$*.cpp.out;"	\
+			echo "ERROR:";												\
+			cat coverage_tmp;											\
+		fi;																\
+	fi
+	@echo "Done"
 	@if [ -e $*.cpp*$*.tpp.gcov ]; then mv $*.cpp*$*.tpp.gcov coverage/$*.tpp.gcov; fi;
 	@if [ -e $*.cpp.gcov ]; then mv $*.cpp.gcov coverage/; fi;
 	@$(RM) *.gcov
